/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d6cf8a94a4f7c744b6c964c
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE productsBaseService PLEASE EDIT ../products.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Products } from '../../domain/choonti_db/products';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Products.service.ts
 */

/*
 * SCHEMA DB Products
 *
	{
		description: {
			type: 'String',
			required : true
		},
		frequency: {
			type: 'Number'
		},
		image: {
			type: 'String'
		},
		name: {
			type: 'String',
			required : true
		},
		price: {
			type: 'Number',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		id: {
			type: Schema.ObjectId,
			ref : "Products"
		},
	}
 *
 */
@Injectable()
export class ProductsBaseService {

    contextUrl: string = environment.endpoint + '/products';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProductsService.findByname
    *   @description CRUD ACTION findByname
    *   @param Objectid key Id of the resource name to search
    *
    */
    findByName(id: string): Observable<Products[]> {
        return this.http
            .get<Products[]>(this.contextUrl + '/findByname/' + id)
            .pipe(
                map(response => response)
            );
    }


    // Custom APIs

}
