/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d6cf8a94a4f7c744b6c964c
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE shopBaseService PLEASE EDIT ../shop.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Shop } from '../../domain/choonti_db/shop';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Shop.service.ts
 */

/*
 * SCHEMA DB Shop
 *
	{
		area: {
			type: 'String',
			required : true
		},
		city: {
			type: 'String',
			required : true
		},
		country: {
			type: 'String',
			required : true
		},
		location: {
			type: 'String'
		},
		name: {
			type: 'String',
			required : true
		},
		qlength: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		id: {
			type: Schema.ObjectId,
			ref : "Products"
		},
	}
 *
 */
@Injectable()
export class ShopBaseService {

    contextUrl: string = environment.endpoint + '/shop';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ShopService.create
    *   @description CRUD ACTION create
    *   @param Shop obj Object to insert
    *
    */
    create(item: Shop): Observable<Shop> {
        return this.http
            .post<Shop>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ShopService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id Shop
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ShopService.findByarea
    *   @description CRUD ACTION findByarea
    *   @param Objectid key Id of the resource area to search
    *
    */
    findByArea(id: string): Observable<Shop[]> {
        return this.http
            .get<Shop[]>(this.contextUrl + '/findByarea/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ShopService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id Shop
    *   @returns Shop
    *
    */
    get(id: string): Observable<Shop> {
        return this.http
            .get<Shop>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ShopService.list
    *   @description CRUD ACTION list
    *   @returns ARRAY OF Shop
    *
    */
    list(): Observable<Shop[]> {
        return this.http
            .get<Shop[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ShopService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id Shop
    *   @returns Shop
    *
    */
    update(item: Shop): Observable<Shop> {
        return this.http
            .post<Shop>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
