/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d6cf8a94a4f7c744b6c964c
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ShopService } from '../../services/shop.service';
// Import Models
import { Shop } from '../../domain/choonti_db/shop';

// START - USED SERVICES
/**
* ShopService.list
*	@description CRUD ACTION list
*	@returns ARRAY OF Shop
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Shop
 * @class ShopListComponent
 */
@Component({
    selector: 'app-shop-list',
    templateUrl: './shop-list.component.html',
    styleUrls: ['./shop-list.component.css']
})
export class ShopListComponent implements OnInit {
    list: Shop[];
    search: any = {};
    idSelected: string;
    constructor(
        private shopService: ShopService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.shopService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Shop to remove
     *
     * @param {string} id Id of the Shop to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Shop
     */
    deleteItem() {
        this.shopService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
